version: "3.9"

services:
  client:
    image: "client/latest"
    build: ./client
    ports:
      - 8081:8081
    volumes:
      - type: bind
        source: ./example.txt
        target: /app/example.txt
      - type: bind
        source: .
        target: /app
    environment:
      user.id: "1"
      folder.path: "/app/folder"
      base.url: "http://server:8080/template"
    depends_on:
      - server

  server:
    image: "server/latest"
    build: ./server
    ports:
      - 8080:8080
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/naijagigs4medb"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "thinkaboutit"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgresdb:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "thinkaboutit"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "naijagigs4medb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
